name       : akonadi-contacts
version    : 19.12.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/akonadi-contacts-19.12.2.tar.xz : 2ffb88875661756476939c2145af731274b13f986f6c66a7fd3eafcd05eb4f8b
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement Contact Management in Akonadi
description: |
    Libraries and daemons to implement Contact Management in Akonadi.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcontacts-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ktextwidgets-devel
    - libboost-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
