name       : akonadi-contacts
version    : 20.12.1
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/akonadi-contacts-20.12.1.tar.xz : 34ab825e7a6e155363fc5d0b2505661dff612a836de9ea8ba5c61f602dd2ac3f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement Contact Management in Akonadi
description: |
    Libraries and daemons to implement Contact Management in Akonadi.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantlee-devel
    - grantleetheme-devel
    - kcontacts-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - libkleo-devel
    - libboost-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
