name       : akonadi-contacts
version    : 22.08.3
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/akonadi-contacts-22.08.3.tar.xz : 1c1ba53d31b7bf5953d7999485fc22c7995a9ef37a0cf5bd14bea1cc03f4f5af
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement Contact Management in Akonadi
description: |
    Libraries and daemons to implement Contact Management in Akonadi.
builddeps  :
    - akonadi-devel
    - gpgme-qt-devel
    - grantleetheme-devel
    - kcmutils-devel
    - kcontacts-devel
    - kiconthemes-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - prison-devel
rundeps    :
    - devel :
        - akonadi-devel
        - grantleetheme-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
