name       : akonadi-contacts
version    : 22.04.3
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/akonadi-contacts-22.04.3.tar.xz : dd3e23b9867c16fef0504cd245e4458cdf37a629f524650f8de9acae11500b20
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement Contact Management in Akonadi
description: |
    Libraries and daemons to implement Contact Management in Akonadi.
builddeps  :
    - akonadi-devel
    - gpgme-qt-devel
    - grantleetheme-devel
    - kcmutils-devel
    - kcontacts-devel
    - kiconthemes-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - prison-devel
rundeps    :
    - devel :
        - akonadi-devel
        - grantleetheme-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
