name       : akonadi-contacts
version    : 20.04.2
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/akonadi-contacts-20.04.2.tar.xz : 9bffeec514cb798e6764ef70c6eb05c524fe84ee6298b3c341c32a8a5a4cdd19
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement Contact Management in Akonadi
description: |
    Libraries and daemons to implement Contact Management in Akonadi.
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcontacts-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - libboost-devel
    - prison-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
