name       : akonadi-contacts
version    : 20.12.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/akonadi-contacts-20.12.2.tar.xz : 7fab1fc1833d80a1a1b0040b723c57546bfa4401d3148a1fc511ea80f7cdc117
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libraries and daemons to implement Contact Management in Akonadi
description: |
    Libraries and daemons to implement Contact Management in Akonadi.
builddeps  :
    - akonadi-devel
    - gpgme-qt-devel
    - grantleetheme-devel
    - kcontacts-devel
    - kiconthemes-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - libkleo-devel
    - prison-devel
rundeps    :
    - devel :
        - akonadi-devel
        - grantleetheme-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
