name       : akonadi-contacts
version    : 17.12.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/akonadi-contacts-17.12.1.tar.xz : 214a9859ebb02a92f84a754f5670b7360c6883d8e2ef032c339f7f053bfffb89
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Libraries and daemons to implement Contact Management in Akonadi.
description: |
    Libraries and daemons to implement Contact Management in Akonadi.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kmime-devel
    - ktextwidgets-devel
    - libboost-devel
    - prison-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
